services:
  - type: web
    name: camera-ecom-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: camerastore
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PAYPAL_CLIENT_ID
        sync: false
